//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlusStokTakip.EntityLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashRegister
    {
        public int CashID { get; set; }
        public string TransactionType { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
    }
}
