//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlusStokTakip.EntityLayer.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlusStokTakipEntities : DbContext
    {
        public PlusStokTakipEntities()
            : base("name=PlusStokTakipEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brands> Brands { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Models> Models { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Shelves> Shelves { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Purchases> Purchases { get; set; }
        public virtual DbSet<Sales> Sales { get; set; }
        public virtual DbSet<StockMovements> StockMovements { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Suppliers> Suppliers { get; set; }
        public virtual DbSet<CashRegister> CashRegister { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<Receipts> Receipts { get; set; }
        public virtual DbSet<BankAccounts> BankAccounts { get; set; }
        public virtual DbSet<BankTransactions> BankTransactions { get; set; }
    }
}
