//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlusStokTakip.EntityLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchases
    {
        public int PurchaseID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public int Quantity { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public decimal Cost { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Suppliers Suppliers { get; set; }
    }
}
