//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlusStokTakip.EntityLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int SaleID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public int Quantity { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> TotalRevenue { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Customers Customers { get; set; }
    }
}
